name: CI workflow for python app
on:
  push:
    branches:
      - "main"
jobs:
  bh-python:
    runs-on: ${{ matrix.ossystem }}
    strategy:
      matrix:
        ossystem: [ubuntu-latest,windows-latest,macos-latest]
    steps:
      - name: checking python version on platform
        run: python -V
      - name: fetching git repo code to runnerrs machine 
        uses: actions/checkout@v4
      - name: run python code into ${{ matrix.ossystem }}
        run: python bh-pyt.py
        